name: Sync to Public Repo

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Private Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to Public Repo
        run: |
          git remote add public https://VKSINGH2596:${{ secrets.PUBLIC_REPO_TOKEN }}@github.com/VKSINGH2596/Udemy-Learnings.git
          git push public main --force
