name: Sync to Public Repo

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches:
      - main
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Private Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history

      - name: Debug Token Check
        run: |
          if [ -z "${{ secrets.PUBLIC_REPO_TOKEN }}" ]; then
            echo "SECRET IS EMPTY!"
          else
            echo "Secret is present"
          fi
          
      - name: Push to Public Repo
        env:
          TOKEN: ${{ secrets.PUBLIC_REPO_TOKEN }}
        run: |
          git remote add public https://VKSINGH2596:$TOKEN@github.com/VKSINGH2596/Udemy-Learnings.git
          git push public main --force
          
